repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.29
    hooks:
      - id: terraform-fmt
      - id: tflint
  - repo: https://github.com/kabisa/terraform-datadog-pre-commit-hook
    rev: "1.3.6"
    hooks:
      - id: terraform-datadog-docs
        args:
          - "."
