apiVersion: backstage.io/v1alpha1 # Do not touch
kind: Component # Do not touch
metadata:
  annotations: 
    github.com/project-slug: worldcoin/terraform-datadog-kubernetes # your github project slug for example worldcoin/infrastructure
  tags: ["code-lang:hcl"] # Replace yourCodeLanguage. Also feel free to add more tags in the format of "key:value".
  description: Your project description # Add your project description
  links: # Feel free to add more links
  - title: Linear # Do not touch
    url: https://yourLinearProjectUrl # A link to your Linear project
  - title: Documentation # Do not touch
    url: https://yourProjectDocumentation # A link to your documentation
  name: terraform-datadog-kubernetes # Should be the Github slug
spec: 
  lifecycle: production # Do not touch
  owner: infrastructure # Should be the exact name of a github team https://github.com/orgs/worldcoin/teams, https://github.com/orgs/worldcoin/teams/engineering/teams
  type: service # Can be service, website, library, or a more specific self defined. https://backstage.io/docs/features/software-catalog/system-model/